name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  version: 1.0.${{ github.run_number }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and publish
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Yarp/Dockerfile
        push: true
        build-args: BUILD_VERSION=${{ env.version }} 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mprproxy:latest , ${{ secrets.DOCKERHUB_USERNAME }}/mprproxy:${{ env.version }}
